package com.niit.entity;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;

/**
 * Admin generated by hbm2java
 */
@Entity
@Table(name="admin")
public class Admin {

	@Id
	@GeneratedValue(generator="system-admin")  
	@GenericGenerator(name="system-admin", strategy = "assigned")  
	@Column(name="AdminNo")
     private String adminNo;
	@Column(name="AdminName")
     private String adminName;
	@Column(name="AdminPwd")
     private String adminPwd;

    public Admin() {
    }

    public Admin(String adminNo, String adminName, String adminPwd) {
       this.adminNo = adminNo;
       this.adminName = adminName;
       this.adminPwd = adminPwd;
    }
   
 
    public String getAdminNo() {
        return this.adminNo;
    }
    
    public void setAdminNo(String adminNo) {
        this.adminNo = adminNo;
    }

    
    public String getAdminName() {
        return this.adminName;
    }
    
    public void setAdminName(String adminName) {
        this.adminName = adminName;
    }

    
    public String getAdminPwd() {
        return this.adminPwd;
    }
    
    public void setAdminPwd(String adminPwd) {
        this.adminPwd = adminPwd;
    }




}


