package com.niit.entity;
// Generated 2018-12-22 11:45:53 by Hibernate Tools 4.3.1



import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Classroom generated by hbm2java
 */
@Entity
@Table(name="Classroom"
    ,schema="dbo"
    ,catalog="Doublezl"
)
public class Classroom {


	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE)
	@Column(name="ClassroomNo")
     private String classroomNo;
	@Column(name="Building")
     private String building;
	@Column(name="RoomNo")
     private String roomNo;
	@Column(name="RoomType")
     private String roomType;
	@Column(name="Capacity")
     private int capacity;

    public Classroom() {
    }

    public Classroom(String classroomNo, String building, String roomNo, String roomType, int capacity) {
       this.classroomNo = classroomNo;
       this.building = building;
       this.roomNo = roomNo;
       this.roomType = roomType;
       this.capacity = capacity;
    }
   
   
    public String getClassroomNo() {
        return this.classroomNo;
    }
    
    public void setClassroomNo(String classroomNo) {
        this.classroomNo = classroomNo;
    }

    
    public String getBuilding() {
        return this.building;
    }
    
    public void setBuilding(String building) {
        this.building = building;
    }

    
    public String getRoomNo() {
        return this.roomNo;
    }
    
    public void setRoomNo(String roomNo) {
        this.roomNo = roomNo;
    }

    
    public String getRoomType() {
        return this.roomType;
    }
    
    public void setRoomType(String roomType) {
        this.roomType = roomType;
    }

    
    public int getCapacity() {
        return this.capacity;
    }
    
    public void setCapacity(int capacity) {
        this.capacity = capacity;
    }




}


