package com.niit.entity;
// Generated 2018-12-22 11:45:53 by Hibernate Tools 4.3.1


import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DivideCourseTableId generated by hbm2java
 */
@Embeddable
public class DivideCourseTableId implements Serializable{

	  @Column(name="CourseNo")
     private String courseNo;
	  @Column(name="JieshuNo")
     private Integer jieshuNo;
//	  
//	  @Column(name="couOrder")
//	  private  Integer couOrder;
//	  @Column(name="Weeks")
//     private Integer weeks;
//	  @Column(name="LseeionTime")
//     private String lseeionTime;
//	  @Column(name="JieshuType")
//     private Integer jieshuType;
//	  @Column(name="ClassroomNo")
//     private String classroomNo;

    public DivideCourseTableId() {
    }

    

  
    public DivideCourseTableId(String courseNo,Integer jieshuNo) {
		this.courseNo = courseNo;
		this.jieshuNo = jieshuNo;
	}




	public String getCourseNo() {
        return this.courseNo;
    }
    
    public void setCourseNo(String courseNo) {
        this.courseNo = courseNo;
    }


  
    public Integer getJieshuNo() {
        return this.jieshuNo;
    }
    
    public void setJieshuNo(Integer jieshuNo) {
        this.jieshuNo = jieshuNo;
    }




	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((courseNo == null) ? 0 : courseNo.hashCode());
		result = prime * result
				+ ((jieshuNo == null) ? 0 : jieshuNo.hashCode());
		return result;
	}




	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		DivideCourseTableId other = (DivideCourseTableId) obj;
		if (courseNo == null) {
			if (other.courseNo != null)
				return false;
		} else if (!courseNo.equals(other.courseNo))
			return false;
		if (jieshuNo == null) {
			if (other.jieshuNo != null)
				return false;
		} else if (!jieshuNo.equals(other.jieshuNo))
			return false;
		return true;
	}




}


