package com.niit.entity;
// Generated 2018-12-22 11:45:53 by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * DivideCourseTable generated by hbm2java
 */
@Entity
@Table(name="dividecoursetable")
public class DivideCourseTable {
   
     @EmbeddedId
 	 @AttributeOverrides( {
         @AttributeOverride(name="courseNo", column=@Column(name="CourseNo") ), 
         @AttributeOverride(name="jieshuNo",column=@Column(name="JieshuNo")),
 	 })
     private DivideCourseTableId id;

	  @Column(name="Weeks")
    private Integer weeks;
	  @Column(name="LseeionTime")
    private String lseeionTime;
	  @Column(name="JieshuType")
    private Integer jieshuType;
	  @Column(name="ClassroomNo")
    private String classroomNo;
	  @Column(name="couOrder")
	  private  Integer couOrder;
	  
	    public DivideCourseTable() {
	    }
	    
		public DivideCourseTable(DivideCourseTableId id, int weeks, String lseeionTime, int jieshuType,
				String classroomNo,int couOrder) {
			this.id = id;
			this.weeks = weeks;
			this.lseeionTime = lseeionTime;
			this.jieshuType = jieshuType;
			this.classroomNo = classroomNo;
			this.couOrder = couOrder;
		}

	  
	public DivideCourseTableId getId() {
		return id;
	}
	public void setId(DivideCourseTableId id) {
		this.id = id;
	}
	public Integer getWeeks() {
		return weeks;
	}
	public void setWeeks(Integer weeks) {
		this.weeks = weeks;
	}
	public String getLseeionTime() {
		return lseeionTime;
	}
	public void setLseeionTime(String lseeionTime) {
		this.lseeionTime = lseeionTime;
	}
	public Integer getJieshuType() {
		return jieshuType;
	}
	public void setJieshuType(Integer jieshuType) {
		this.jieshuType = jieshuType;
	}
	public String getClassroomNo() {
		return classroomNo;
	}
	public void setClassroomNo(String classroomNo) {
		this.classroomNo = classroomNo;
	}
	public Integer getCouOrder() {
		return couOrder;
	}
	public void setCouOrder(Integer couOrder) {
		this.couOrder = couOrder;
	}
	  

}


