package com.niit.entity;
// Generated 2018-12-22 11:45:53 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * StudentCourseId generated by hbm2java
 */
@Embeddable
public class SestudentCourseId  implements java.io.Serializable {

	@Column(name="StuNo", nullable=false, length=15)
     private String stuNo;
    @Column(name="CourseNo")
     private String courseNo;
     @Column(name="CouOrder")
    private  Integer couOrder;
    @Column(name="Years", nullable=false, length=4)
     private String years;
    @Column(name="term", nullable=false)
     private String term;

    public SestudentCourseId() {
    }

 





	public SestudentCourseId(String stuNo, String courseNo, Integer couOrder, String years, String term) {
		this.stuNo = stuNo;
		this.courseNo = courseNo;
		this.couOrder = couOrder;
		this.years = years;
		this.term = term;
	}







	public String getStuNo() {
        return this.stuNo;
    }
    
    public void setStuNo(String stuNo) {
        this.stuNo = stuNo;
    }



    public String getCourseNo() {
        return this.courseNo;
    }
    
    public void setCourseNo(String courseNo) {
        this.courseNo = courseNo;
    }


  
	public Integer getCouOrder() {
		return couOrder;
	}

	public void setCouOrder(Integer couOrder) {
		this.couOrder = couOrder;
	}

	public String getYears() {
        return this.years;
    }
    
    public void setYears(String years) {
        this.years = years;
    }


 
    public String getTerm() {
        return this.term;
    }
    
    public void setTerm(String term) {
        this.term = term;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SestudentCourseId) ) return false;
		 SestudentCourseId castOther = ( SestudentCourseId ) other; 
         
		 return ( (this.getStuNo()==castOther.getStuNo()) || ( this.getStuNo()!=null && castOther.getStuNo()!=null && this.getStuNo().equals(castOther.getStuNo()) ) )
 && ( (this.getCourseNo()==castOther.getCourseNo()) || ( this.getCourseNo()!=null && castOther.getCourseNo()!=null && this.getCourseNo().equals(castOther.getCourseNo()) ) )
 && ( (this.getCouOrder()==castOther.getCouOrder()) || ( this.getCouOrder()!=null && castOther.getCouOrder()!=null && this.getCouOrder().equals(castOther.getCouOrder()) ) )
 && ( (this.getYears()==castOther.getYears()) || ( this.getYears()!=null && castOther.getYears()!=null && this.getYears().equals(castOther.getYears()) ) )
 && ( (this.getTerm()==castOther.getTerm()) || ( this.getTerm()!=null && castOther.getTerm()!=null && this.getTerm().equals(castOther.getTerm()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getStuNo() == null ? 0 : this.getStuNo().hashCode() );
         result = 37 * result + ( getCourseNo() == null ? 0 : this.getCourseNo().hashCode() );
         result = 37 * result + ( getCouOrder() == null ? 0 : this.getCouOrder().hashCode() );
         result = 37 * result + ( getYears() == null ? 0 : this.getYears().hashCode() );
         result = 37 * result + ( getTerm() == null ? 0 : this.getTerm().hashCode() );
         return result;
   }   


}


