package com.niit.entity;
// Generated 2018-12-22 11:45:53 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
 
/**
 * Batch generated by hbm2java
 */
@Entity
@Table(name="batch")
public class Batch{


	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE)
	@Column(name="BatNo")
     private String batNo;
	@Column(name="BatName")
     private String batName;
	@Column(name="BatNum")
     private Integer batNum;
	@Column(name="MajNo")
     private String majNo;

    public Batch() {
    }

	
    public Batch(String batNo, String batName, String majNo) {
        this.batNo = batNo;
        this.batName = batName;
        this.majNo = majNo;
    }
    public Batch(String batNo, String batName, Integer batNum, String majNo) {
       this.batNo = batNo;
       this.batName = batName;
       this.batNum = batNum;
       this.majNo = majNo;
    }
   
 
    public String getBatNo() {
        return this.batNo;
    }
    
    public void setBatNo(String batNo) {
        this.batNo = batNo;
    }

    
    public String getBatName() {
        return this.batName;
    }
    
    public void setBatName(String batName) {
        this.batName = batName;
    }

    
    public Integer getBatNum() {
        return this.batNum;
    }
    
    public void setBatNum(Integer batNum) {
        this.batNum = batNum;
    }

    
    public String getMajNo() {
        return this.majNo;
    }
    
    public void setMajNo(String majNo) {
        this.majNo = majNo;
    }




}


