package com.niit.entity;
// Generated 2018-12-22 11:45:53 by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;

import javax.persistence.Table;

/**
 * Course generated by hbm2java
 */
@Entity
@Table(name="course")
public class Course {

	
	@EmbeddedId
	@AttributeOverrides( {
        @AttributeOverride(name="courseNo", column=@Column(name="CourseNo") ), 
        @AttributeOverride(name="couOrder",column=@Column(name="CouOrder")),
	})
	private CourseId id;
	
	@Column(name="CourseName")
     private String courseName;
	@Column(name="CourseType")
     private String courseType;
	@Column(name="AcaNo")
     private String acaNo;
	@Column(name="CourseCredit")
     private int courseCredit;
	@Column(name="CourseDesc")
     private String courseDesc;

    public Course() {
    }
    
	public Course(CourseId id, String courseName, String courseType, String acaNo, int courseCredit,
			String courseDesc) {
		this.id = id;
		this.courseName = courseName;
		this.courseType = courseType;
		this.acaNo = acaNo;
		this.courseCredit = courseCredit;
		this.courseDesc = courseDesc;
	}




	public CourseId getId() {
		return id;
	}

	public void setId(CourseId id) {
		this.id = id;
	}




	public String getCourseName() {
        return this.courseName;
    }
    
    public void setCourseName(String courseName) {
        this.courseName = courseName;
    }

    
    public String getCourseType() {
        return this.courseType;
    }
    
    public void setCourseType(String courseType) {
        this.courseType = courseType;
    }

    
    public String getAcaNo() {
        return this.acaNo;
    }
    
    public void setAcaNo(String acaNo) {
        this.acaNo = acaNo;
    }

    
    public int getCourseCredit() {
        return this.courseCredit;
    }
    
    public void setCourseCredit(int courseCredit) {
        this.courseCredit = courseCredit;
    }

    
    public String getCourseDesc() {
        return this.courseDesc;
    }
    
    public void setCourseDesc(String courseDesc) {
        this.courseDesc = courseDesc;
    }




}


