package com.niit.entity;
// Generated 2018-12-22 11:45:53 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
 
/**
 * Batch generated by hbm2java
 */
@Entity
@Table(name="message")
public class Message{


	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name="MessageId")
     private String messageId;
	@Column(name="Content")
     private String content;
	@Column(name="LeaveWordTime")
     private String leaveWordTime;
	@Column(name="StuNo")
     private Integer stuNo;
	@Column(name="Replay")
    private String replay;
	@Column(name="ReplayTime")
    private String replayTime;
	
	public Message() {
		super();
	}
	public Message(String messageId, String content, String leaveWordTime, Integer stuNo, String replay,
			String replayTime) {
		super();
		this.messageId = messageId;
		this.content = content;
		this.leaveWordTime = leaveWordTime;
		this.stuNo = stuNo;
		this.replay = replay;
		this.replayTime = replayTime;
	}
	public String getMessageId() {
		return messageId;
	}
	public void setMessageId(String messageId) {
		this.messageId = messageId;
	}
	public String getContent() {
		return content;
	}
	public void setContent(String content) {
		this.content = content;
	}
	
	public String getLeaveWordTime() {
		return leaveWordTime;
	}
	public void setLeaveWordTime(String leaveWordTime) {
		this.leaveWordTime = leaveWordTime;
	}
	public Integer getStuNo() {
		return stuNo;
	}
	public void setStuNo(Integer stuNo) {
		this.stuNo = stuNo;
	}
	public String getReplay() {
		return replay;
	}
	public void setReplay(String replay) {
		this.replay = replay;
	}
	public String getReplayTime() {
		return replayTime;
	}
	public void setReplayTime(String replayTime) {
		this.replayTime = replayTime;
	}



}


