package com.niit.entity;
// Generated 2018-12-22 11:45:53 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Teacher generated by hbm2java
 */
@Entity
@Table(name="teacher")  
public class Teacher {

    @Id 
    @GeneratedValue(strategy = GenerationType.SEQUENCE)
    @Column(name="TeaNo", unique=true, nullable=false, length=10)
     private String teaNo;
    @Column(name="TeaName", nullable=false)
     private String teaName;
    @Column(name="TeaPass", nullable=false, length=16)
     private String teaPass;  
    @Column(name="Gender", nullable=false)
     private String gender;
    
    @Temporal(TemporalType.DATE)  
    @Column(name="Birthdate", nullable=false, length=10)
     private Date birthdate;
    
    @Column(name="Email", length=25)
     private String email;
    @Column(name="AcaNo", nullable=false, length=4)
     private String acaNo;

    public Teacher() {
    }

	
    public Teacher(String teaNo, String teaName, String teaPass, String gender, Date birthdate, String acaNo) {
        this.teaNo = teaNo;
        this.teaName = teaName;
        this.teaPass = teaPass;
        this.gender = gender;
        this.birthdate = birthdate;
        this.acaNo = acaNo;
    }
    public Teacher(String teaNo, String teaName, String teaPass, String gender, Date birthdate, String email, String acaNo) {
       this.teaNo = teaNo;
       this.teaName = teaName;
       this.teaPass = teaPass;
       this.gender = gender;
       this.birthdate = birthdate;
       this.email = email;
       this.acaNo = acaNo;
    }
   

    public String getTeaNo() {
        return this.teaNo;
    }
    
    public void setTeaNo(String teaNo) {
        this.teaNo = teaNo;
    }

    

    public String getTeaName() {
        return this.teaName;
    }
    
    public void setTeaName(String teaName) {
        this.teaName = teaName;
    }

    
   
    public String getTeaPass() {
        return this.teaPass;
    }
    
    public void setTeaPass(String teaPass) {
        this.teaPass = teaPass;
    }

    
  
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }

   
    public Date getBirthdate() {
        return this.birthdate;
    }
    
    public void setBirthdate(Date birthdate) {
        this.birthdate = birthdate;
    }

    
   
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
   
    public String getAcaNo() {
        return this.acaNo;
    }
    
    public void setAcaNo(String acaNo) {
        this.acaNo = acaNo;
    }




}


